name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install node modules
        uses: bahmutov/npm-install@v1

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint -- --max-warnings=0

      - name: Type check
        run: npm run typeCheck

      - name: Test
        run: npm run test -- --coverage

      - name: Build storybook
        run: npm run build-storybook -- --quiet

      - name: Upload pages artifacts
        # https://github.com/actions/upload-pages-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'storybook-static'

      - name: Deploy GitHub Pages
        if: github.ref == 'refs/heads/main'
        # https://github.com/actions/deploy-pages
        uses: actions/deploy-pages@v4
